Repository AJD-Archive/Kkeujeok_Backend, pull requests merged in 2024-11, with the labels that each got.

#200 Feat(#197): 친구 추가 요청, 수락, 예외처리 로직
  src/docs/asciidoc/follow.adoc
  src/main/java/shop/kkeujeok/kkeujeokbackend/member/domain/Member.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/member/follow/api/FollowController.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/member/follow/api/dto/request/FollowAcceptReqDto.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/member/follow/api/dto/request/FollowReqDto.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/member/follow/api/dto/response/FollowAcceptResDto.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/member/follow/api/dto/response/FollowInfoListDto.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/member/follow/api/dto/response/FollowInfoResDto.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/member/follow/api/dto/response/FollowResDto.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/member/follow/api/dto/response/RecommendedFollowInfoListDto.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/member/follow/api/dto/response/RecommendedFollowInfoResDto.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/member/follow/application/FollowService.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/member/follow/domain/Follow.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/member/follow/domain/FollowStatus.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/member/follow/domain/repository/FollowCustomRepository.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/member/follow/domain/repository/FollowCustomRepositoryImpl.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/member/follow/domain/repository/FollowRepository.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/member/follow/exception/FollowAlreadyExistsException.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/member/follow/exception/FollowNotFoundException.java
  src/test/java/shop/kkeujeok/kkeujeokbackend/common/annotation/ControllerTest.java
  src/test/java/shop/kkeujeok/kkeujeokbackend/member/follow/api/FollowControllerTest.java
Labels: Feature

#202 Refactor: 블록 마감기함 하루 남았을 때 알림 보내는 기능 추가
  src/main/java/shop/kkeujeok/kkeujeokbackend/block/application/BlockService.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/block/util/BlockDeadlineNotifier.java
Labels: Refactor

#204 Feat: 친구 신청 시 알림 전송 기능 추가
  src/main/java/shop/kkeujeok/kkeujeokbackend/block/application/BlockService.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/member/follow/application/FollowService.java
  src/test/java/shop/kkeujeok/kkeujeokbackend/block/application/BlockServiceTest.java
Labels: Feature

#205 Refactor: 친구 신청 알림 메시지 수정
  src/main/java/shop/kkeujeok/kkeujeokbackend/member/follow/application/FollowService.java
Labels: Refactor

#207 Refactor: 프론트 요청에 따라 친구 초대 알림 메시지 변경
  src/main/java/shop/kkeujeok/kkeujeokbackend/member/follow/application/FollowService.java
Labels: Refactor

#208 Refactor: 팀 대시보드 친구 초대 알림 메시지 수정
  src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/team/application/TeamDashboardService.java
Labels: Refactor

#210 Refactor(#197): 내 친구 목록 조건 수정
  src/main/java/shop/kkeujeok/kkeujeokbackend/member/follow/domain/repository/FollowCustomRepositoryImpl.java
Labels: Refactor

#211 Refactor(#197): 내 친구 목록 isFollow 값 반환 , 내 친구 숫자 반환 api 생성
  src/docs/asciidoc/follow.adoc
  src/main/java/shop/kkeujeok/kkeujeokbackend/member/follow/api/FollowController.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/member/follow/api/dto/response/FollowInfoResDto.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/member/follow/api/dto/response/MyFollowsResDto.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/member/follow/api/dto/response/RecommendedFollowInfoResDto.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/member/follow/application/FollowService.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/member/follow/domain/repository/FollowCustomRepository.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/member/follow/domain/repository/FollowCustomRepositoryImpl.java
  src/test/java/shop/kkeujeok/kkeujeokbackend/member/follow/api/FollowControllerTest.java
Labels: Feature, Refactor, Test

#216 Refactor(#197): 개인 대시보드 상세 조회 예외 검증 수정, 블록 권한 제어, 휴지통 전체 삭제 기능 추가, 삭제된 블록 30일 이후 영구 삭제 기능 추가
  src/docs/asciidoc/block.adoc
  src/main/java/shop/kkeujeok/kkeujeokbackend/block/api/BlockController.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/block/application/BlockService.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/block/application/util/BlockCleanupScheduler.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/block/domain/repository/BlockCustomRepository.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/block/domain/repository/BlockCustomRepositoryImpl.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/personal/application/PersonalDashboardService.java
  src/test/java/shop/kkeujeok/kkeujeokbackend/block/api/BlockControllerTest.java
  src/test/java/shop/kkeujeok/kkeujeokbackend/block/application/BlockServiceTest.java
Labels: Docs, API, Feature, Refactor, Test

#215 Refactor(#197): 친구 수락 중복시 에러처리, 친구 검색 이름으로도 가능하게, 친구 마이페이지 조회 api 구현
  src/docs/asciidoc/member.adoc
  src/main/java/shop/kkeujeok/kkeujeokbackend/member/api/MemberController.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/member/follow/domain/repository/FollowCustomRepositoryImpl.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/member/follow/exception/FollowAlreadyAcceptException.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/member/mypage/api/dto/response/PersonalDashboardsAndChallengesResDto.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/member/mypage/application/MyPageService.java
  src/test/java/shop/kkeujeok/kkeujeokbackend/member/api/MemberControllerTest.java
Labels: Feature, Refactor, Test

#220 Feature: 챌린지 블록이 시작전에 5개 이상 쌓이면 탈퇴하도록 변경
  src/main/java/shop/kkeujeok/kkeujeokbackend/challenge/application/util/ChallengeBlockStatusUpdateScheduler.java
Labels: Refactor

#225 Feat(#197): 내 정보 조회할 때 memberId도 나오도록 수정
  src/main/java/shop/kkeujeok/kkeujeokbackend/member/mypage/api/dto/response/MyPageInfoResDto.java
  src/test/java/shop/kkeujeok/kkeujeokbackend/member/api/MemberControllerTest.java
  src/test/java/shop/kkeujeok/kkeujeokbackend/member/mypage/application/MyPageServiceTest.java
Labels: Feature

#227 Refactor: 챌린지 반환 타입에 챌린지 작성자 추가
  src/main/java/shop/kkeujeok/kkeujeokbackend/challenge/api/dto/response/ChallengeInfoResDto.java
  src/test/java/shop/kkeujeok/kkeujeokbackend/challenge/api/ChallengeControllerTest.java
Labels: Refactor
