Repository AJD-Archive/Kkeujeok_Backend, pull requests merged in 2024-12, with the labels that each got.

#234 Refactor(#233): 팀 대시보드 초대 조건 수정
  src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/team/api/dto/request/TeamDashboardSaveReqDto.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/team/api/dto/request/TeamDashboardUpdateReqDto.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/team/application/TeamDashboardService.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/member/domain/repository/MemberRepository.java
  src/test/java/shop/kkeujeok/kkeujeokbackend/dashboard/team/api/TeamDashboardControllerTest.java
  src/test/java/shop/kkeujeok/kkeujeokbackend/dashboard/team/application/TeamDashboardServiceTest.java
Labels: Feature, Refactor

#237 Refactor: 내 프로필 정보 반환 값 수정
  src/main/java/shop/kkeujeok/kkeujeokbackend/member/mypage/api/dto/response/MyPageInfoResDto.java
Labels: Refactor

#240 fix: 챌린지 주기 수정 안되는 오류 해결
  src/main/java/shop/kkeujeok/kkeujeokbackend/challenge/application/ChallengeService.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/challenge/domain/Challenge.java
  src/test/java/shop/kkeujeok/kkeujeokbackend/challenge/domain/ChallengeTest.java
Labels: Bug

#242 fix: 챌린지 주기 수정 안되는 오류 해결
  src/main/java/shop/kkeujeok/kkeujeokbackend/challenge/domain/Challenge.java
Labels: Bug

#249 fix: 친구 수락 알림 메시지 수정
  src/main/java/shop/kkeujeok/kkeujeokbackend/member/follow/application/FollowService.java
Labels: Bug

#250 운영 서버 배포를 위한 PR
  src/main/java/shop/kkeujeok/kkeujeokbackend/member/follow/application/FollowService.java
Labels: devops

#252 Fix: 이미지 업로드 안 되는 오류 해결
  src/main/java/shop/kkeujeok/kkeujeokbackend/global/aws/S3Service.java
Labels: Bug

#254 Refactor(#235): 블록 인덱스 설정
  src/main/java/shop/kkeujeok/kkeujeokbackend/block/domain/Block.java
Labels: Refactor

#256 Feat(#255): 공지 조회 기능 구현
  src/main/java/shop/kkeujeok/kkeujeokbackend/amdin/api/NoticeController.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/amdin/api/response/NoticeInfoResDto.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/amdin/api/response/NoticeListResDto.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/amdin/application/NoticeService.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/amdin/domain/Notice.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/amdin/domain/repository/NoticeRepository.java
Labels: Feature
