Repository AJD-Archive/Kkeujeok_Backend, pull requests merged in 2024-09, with the labels that each got.

#98 Refactor(#18): 테스트 코드 페이지, 사이즈 파라미터 추가
  src/test/java/shop/kkeujeok/kkeujeokbackend/block/api/BlockControllerTest.java
Labels: Refactor, Test

#99 Refactor(#74): 팀 대시보드 초대 시 알림 발송 API 추가
  src/main/java/shop/kkeujeok/kkeujeokbackend/challenge/application/ChallengeService.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/exception/InvalidMemberInviteException.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/team/api/TeamDashboardController.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/team/application/TeamDashboardService.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/global/config/SchedulerConfig.java
  src/test/java/shop/kkeujeok/kkeujeokbackend/dashboard/team/api/TeamDashboardControllerTest.java
  src/test/java/shop/kkeujeok/kkeujeokbackend/dashboard/team/application/TeamDashboardServiceTest.java
Labels: Feature, Refactor

#102 Refactor(#74): 팀 대시보드 생성 및 수정 시 팀 초대 알림 가도록 변경
  src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/team/api/TeamDashboardController.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/team/api/dto/request/TeamDashboardSaveReqDto.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/team/api/dto/request/TeamDashboardUpdateReqDto.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/team/application/TeamDashboardService.java
  src/test/java/shop/kkeujeok/kkeujeokbackend/dashboard/team/api/TeamDashboardControllerTest.java
  src/test/java/shop/kkeujeok/kkeujeokbackend/dashboard/team/application/TeamDashboardServiceTest.java
Labels: Refactor

#105 Refactor(#104): Response에 챌린지 id 추가
  src/main/java/shop/kkeujeok/kkeujeokbackend/challenge/api/dto/response/ChallengeInfoResDto.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/challenge/application/util/ChallengeBlockStatusUpdateScheduler.java
  src/test/java/shop/kkeujeok/kkeujeokbackend/challenge/api/ChallengeControllerTest.java
Labels: Refactor

#103 Refactor: authServiceFactory로 id토큰 반환하는 로직 수정, JsonNode 반환 방법 DTO 사용
  src/main/java/shop/kkeujeok/kkeujeokbackend/auth/api/AuthController.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/auth/api/dto/response/IdTokenResDto.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/auth/application/AuthService.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/auth/application/AuthServiceFactory.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/global/oauth/GoogleAuthService.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/global/oauth/KakaoAuthService.java
Labels: Refactor

#107 Feat(#106): 팀 문서 전체적인 작업
  src/docs/asciidoc/teamDocument.adoc
  src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/teamdoc/api/TeamDocumentController.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/teamdoc/api/dto/request/FindTeamDocumentReqDto.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/teamdoc/api/dto/request/TeamDocumentReqDto.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/teamdoc/api/dto/request/TeamDocumentUpdateReqDto.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/teamdoc/api/dto/response/FindTeamDocumentResDto.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/teamdoc/api/dto/response/TeamDocumentCategoriesResDto.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/teamdoc/api/dto/response/TeamDocumentDetailResDto.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/teamdoc/api/dto/response/TeamDocumentResDto.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/teamdoc/application/TeamDocumentService.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/teamdoc/domain/TeamDocument.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/teamdoc/domain/repository/TeamDocumentCustomRepository.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/teamdoc/domain/repository/TeamDocumentCustomRepositoryImpl.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/teamdoc/domain/repository/TeamDocumentRepository.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/teamdoc/exception/TeamDocumentNotFoundException.java
  src/test/java/shop/kkeujeok/kkeujeokbackend/dashboard/teamdoc/api/TeamDocumentControllerTest.java
Labels: Feature

#113 Refactor(#112): 사용자 사진 반환 값 추가
  src/main/java/shop/kkeujeok/kkeujeokbackend/block/api/dto/response/BlockInfoResDto.java
  src/test/java/shop/kkeujeok/kkeujeokbackend/block/api/BlockControllerTest.java
  src/test/java/shop/kkeujeok/kkeujeokbackend/challenge/api/ChallengeControllerTest.java
Labels: Refactor, Test

#111 Refactor(#110): 대시보드 접근 권한 수정, 카테고리 중복 수정
  src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/domain/repository/DashboardCustomRepository.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/domain/repository/DashboardCustomRepositoryImpl.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/exception/UnauthorizedAccessException.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/personal/api/PersonalDashboardController.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/personal/api/dto/response/PersonalDashboardCategoriesResDto.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/personal/application/PersonalDashboardService.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/team/application/TeamDashboardService.java
  src/test/java/shop/kkeujeok/kkeujeokbackend/dashboard/personal/api/PersonalDashboardControllerTest.java
  src/test/java/shop/kkeujeok/kkeujeokbackend/dashboard/personal/application/PersonalDashboardServiceTest.java
Labels: Refactor

#128 Refacotr(#127): 팀원이 팀 초대 수락하면 팀장한테 알람가도록 구현 및 팀 초대 api 로직 수정
  src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/team/application/TeamDashboardService.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/notification/domain/repository/NotificationCustomRepositoryImpl.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/notification/util/SseEmitterManager.java
Labels: Refactor

#129 Refacor: 알림 연결 성공시 더미데이터 반환
  src/main/java/shop/kkeujeok/kkeujeokbackend/notification/util/SseEmitterManager.java
Labels: Refactor

#135 Refactor(#97): 챌린지 코드 리펙토링
  src/main/java/shop/kkeujeok/kkeujeokbackend/challenge/api/dto/reqeust/ChallengeSaveReqDto.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/challenge/api/dto/response/ChallengeInfoResDto.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/challenge/application/ChallengeService.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/challenge/application/util/ChallengeBlockStatusUpdateScheduler.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/challenge/application/util/ChallengeBlockStatusUtil.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/challenge/domain/Challenge.java
  src/test/java/shop/kkeujeok/kkeujeokbackend/challenge/api/ChallengeControllerTest.java
  src/test/java/shop/kkeujeok/kkeujeokbackend/challenge/application/ChallengeServiceTest.java
  src/test/java/shop/kkeujeok/kkeujeokbackend/challenge/application/util/ChallengeBlockStatusUtilTest.java
  src/test/java/shop/kkeujeok/kkeujeokbackend/challenge/domain/ChallengeTest.java
Labels: Refactor

#140 Docs(#139): 카테고리 별 검색 문서에 추가 및 쿼리 파라미터 추가
  src/docs/asciidoc/challenge.adoc
  src/test/java/shop/kkeujeok/kkeujeokbackend/challenge/api/ChallengeControllerTest.java
Labels: Docs, Test

#142 Feature(#141): 이미지 업로드 기능 추가
  build.gradle
  src/docs/asciidoc/challenge.adoc
  src/main/java/shop/kkeujeok/kkeujeokbackend/challenge/api/ChallengeController.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/challenge/api/dto/reqeust/ChallengeSaveReqDto.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/challenge/application/ChallengeService.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/challenge/domain/Challenge.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/global/aws/S3Service.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/global/aws/exception/InvalidImageUploadException.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/global/config/S3Config.java
  src/test/java/shop/kkeujeok/kkeujeokbackend/challenge/api/ChallengeControllerTest.java
  src/test/java/shop/kkeujeok/kkeujeokbackend/challenge/application/ChallengeServiceTest.java
  src/test/java/shop/kkeujeok/kkeujeokbackend/challenge/domain/ChallengeTest.java
  src/test/java/shop/kkeujeok/kkeujeokbackend/common/annotation/ControllerTest.java
Labels: Docs, Feature, Test

#143 Refcator(#141): url 고유하도록 변경
  src/main/java/shop/kkeujeok/kkeujeokbackend/global/aws/S3Service.java
Labels: Refactor

#145 Refactor(#144): 알림 전체조회 페이지네이션 삭제
  src/docs/asciidoc/notification.adoc
  src/main/java/shop/kkeujeok/kkeujeokbackend/notification/api/NotificationController.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/notification/api/dto/response/NotificationInfoResDto.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/notification/api/dto/response/NotificationListResDto.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/notification/application/NotificationService.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/notification/domain/repository/NotificationCustomRepository.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/notification/domain/repository/NotificationCustomRepositoryImpl.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/notification/domain/repository/NotificationRepository.java
  src/test/java/shop/kkeujeok/kkeujeokbackend/challenge/api/ChallengeControllerTest.java
  src/test/java/shop/kkeujeok/kkeujeokbackend/notification/api/NotificationControllerTest.java
  src/test/java/shop/kkeujeok/kkeujeokbackend/notification/application/NotificationServiceTest.java
Labels: Refactor, Test

#147 Feat(#146): 모든 알림 읽음으로 표시하는 api 추가
  src/docs/asciidoc/notification.adoc
  src/main/java/shop/kkeujeok/kkeujeokbackend/notification/api/NotificationController.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/notification/api/dto/response/NotificationInfoResDto.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/notification/application/NotificationService.java
  src/test/java/shop/kkeujeok/kkeujeokbackend/notification/api/NotificationControllerTest.java
  src/test/java/shop/kkeujeok/kkeujeokbackend/notification/application/NotificationServiceTest.java
Labels: Feature, Test

#149 Refactor(#148): 챌린지 카테고리 및 키워드 검색 api 하나로 통합
  src/docs/asciidoc/challenge.adoc
  src/main/java/shop/kkeujeok/kkeujeokbackend/challenge/api/ChallengeController.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/challenge/api/dto/reqeust/ChallengeSearchReqDto.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/challenge/application/ChallengeService.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/challenge/domain/repository/ChallengeCustomRepository.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/challenge/domain/repository/ChallengeCustomRepositoryImpl.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/global/aws/S3Service.java
  src/test/java/shop/kkeujeok/kkeujeokbackend/challenge/api/ChallengeControllerTest.java
  src/test/java/shop/kkeujeok/kkeujeokbackend/challenge/application/ChallengeServiceTest.java
Labels: Refactor, Test

#152 Refactor: 마이페이지 내에서 개인 대시보드 조회 기능 추가 & 상대방 프로필은 isPublic이 true인 것만 보이도록 수정
  src/docs/asciidoc/member.adoc
  src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/domain/repository/DashboardCustomRepository.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/domain/repository/DashboardCustomRepositoryImpl.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/personal/api/dto/response/PersonalDashboardPageListResDto.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/personal/application/PersonalDashboardService.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/member/api/MemberController.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/member/mypage/api/dto/response/TeamDashboardsAndChallengesResDto.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/member/mypage/application/MyPageService.java
  src/test/java/shop/kkeujeok/kkeujeokbackend/member/api/MemberControllerTest.java
  src/test/java/shop/kkeujeok/kkeujeokbackend/member/mypage/application/MyPageServiceTest.java
Labels: Docs, Refactor, Test

#154 Refactor(#153): 챌린지 상세조회 반환값 수정
  src/main/java/shop/kkeujeok/kkeujeokbackend/challenge/api/ChallengeController.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/challenge/api/dto/response/ChallengeInfoResDto.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/challenge/application/ChallengeService.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/challenge/domain/Challenge.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/challenge/domain/ChallengeMemberMapping.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/member/domain/Member.java
  src/test/java/shop/kkeujeok/kkeujeokbackend/challenge/api/ChallengeControllerTest.java
  src/test/java/shop/kkeujeok/kkeujeokbackend/challenge/application/ChallengeServiceTest.java
Labels: Refactor

#156 Refactor(#155): 팀 대시보드 중복 참여, 참여하지 않았지만 탈퇴하려는 사용자 예외 처리, 참가자 팀 대시보드 리스트 수정
  src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/domain/repository/DashboardCustomRepository.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/domain/repository/DashboardCustomRepositoryImpl.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/team/application/TeamDashboardService.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/team/domain/TeamDashboard.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/team/exception/AlreadyJoinedTeamException.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/team/exception/NotMemberOfTeamException.java
  src/test/java/shop/kkeujeok/kkeujeokbackend/dashboard/team/application/TeamDashboardServiceTest.java
Labels: Refactor, Test

#157 Refactor(#153): 챌린지 실시간 완료자 반환하도록 수정
  src/main/java/shop/kkeujeok/kkeujeokbackend/block/application/BlockService.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/challenge/api/dto/response/ChallengeCompletedMemberInfoResDto.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/challenge/api/dto/response/ChallengeInfoResDto.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/challenge/application/ChallengeService.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/challenge/domain/Challenge.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/challenge/domain/ChallengeMemberMapping.java
  src/test/java/shop/kkeujeok/kkeujeokbackend/challenge/api/ChallengeControllerTest.java
Labels: Refactor

#159 Fix(#158): 이전 팀 문서 삭제
  src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/team/domain/TeamDashboard.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/teamdoc/domain/TeamDocument.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/teamdoc/domain/repository/TeamDocumentCustomRepositoryImpl.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/teamdocument/api/DocumentController.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/teamdocument/api/FileController.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/teamdocument/api/dto/request/DocumentInfoReqDto.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/teamdocument/api/dto/request/DocumentUpdateReqDto.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/teamdocument/api/dto/request/FileInfoReqDto.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/teamdocument/api/dto/response/DocumentInfoResDto.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/teamdocument/api/dto/response/DocumentListResDto.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/teamdocument/api/dto/response/FileInfoResDto.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/teamdocument/api/dto/response/FileListResDto.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/teamdocument/application/DocumentService.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/teamdocument/application/FileService.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/teamdocument/domain/Document.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/teamdocument/domain/File.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/teamdocument/domain/repository/DocumentCustomRepository.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/teamdocument/domain/repository/DocumentCustomRepositoryImpl.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/teamdocument/domain/repository/DocumentRepository.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/teamdocument/domain/repository/FileCustomRepository.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/teamdocument/domain/repository/FileCustomRepositoryImpl.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/teamdocument/domain/repository/FileRepository.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/teamdocument/exception/DocumentNotFoundException.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/teamdocument/exception/FileNotFoundException.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/teamdocument/exception/TeamDashboardNotFoundException.java
  src/test/java/shop/kkeujeok/kkeujeokbackend/common/annotation/ControllerTest.java
  src/test/java/shop/kkeujeok/kkeujeokbackend/dashboard/teamdocument/api/DocumentControllerTest.java
  src/test/java/shop/kkeujeok/kkeujeokbackend/dashboard/teamdocument/api/FileControllerTest.java
  src/test/java/shop/kkeujeok/kkeujeokbackend/dashboard/teamdocument/application/DocumentServiceTest.java
  src/test/java/shop/kkeujeok/kkeujeokbackend/dashboard/teamdocument/application/FileServiceTest.java
  src/test/java/shop/kkeujeok/kkeujeokbackend/dashboard/teamdocument/domain/DocumentTest.java
  src/test/java/shop/kkeujeok/kkeujeokbackend/dashboard/teamdocument/domain/FileTest.java
  src/test/java/shop/kkeujeok/kkeujeokbackend/dashboard/teamdocument/domain/repository/DocumentRepositoryTest.java
  src/test/java/shop/kkeujeok/kkeujeokbackend/dashboard/teamdocument/domain/repository/FileRepositoryTest.java
Labels: Refactor

#160 Refactor(#153): 챌린지 주기마다 블록이 새로 생성되도록 변경
  src/main/java/shop/kkeujeok/kkeujeokbackend/challenge/api/ChallengeController.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/challenge/application/ChallengeService.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/challenge/application/util/ChallengeBlockStatusUpdateScheduler.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/challenge/domain/Challenge.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/challenge/domain/ChallengeMemberMapping.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/challenge/domain/repository/ChallengeCustomRepository.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/challenge/domain/repository/ChallengeCustomRepositoryImpl.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/challenge/domain/repository/challengeMemberMapping/ChallengeMemberMappingCustomRepository.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/challenge/domain/repository/challengeMemberMapping/ChallengeMemberMappingCustomRepositoryImpl.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/challenge/domain/repository/challengeMemberMapping/ChallengeMemberMappingRepository.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/personal/domain/PersonalDashboard.java
  src/test/java/shop/kkeujeok/kkeujeokbackend/challenge/api/ChallengeControllerTest.java
  src/test/java/shop/kkeujeok/kkeujeokbackend/challenge/application/ChallengeServiceTest.java
Labels: Refactor

#162 Fix(#161): 이미지 수정 시 null 반환하는 오류 해결
  src/main/java/shop/kkeujeok/kkeujeokbackend/challenge/application/ChallengeService.java
Labels: Bug

#164 Fix(#163): 매개변수 순서 수정
  src/main/java/shop/kkeujeok/kkeujeokbackend/challenge/application/ChallengeService.java
Labels: Refactor

#166 Feat(#165): 챌린지 탈퇴 api 추가"
  src/docs/asciidoc/challenge.adoc
  src/main/java/shop/kkeujeok/kkeujeokbackend/challenge/api/ChallengeController.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/challenge/api/dto/response/ChallengeCompletedMemberInfoResDto.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/challenge/application/ChallengeService.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/challenge/domain/Challenge.java
  src/test/java/shop/kkeujeok/kkeujeokbackend/challenge/api/ChallengeControllerTest.java
Labels: Feature

#171 Fix(#170): 챌린지 생성 안되는 오류 해결"
  src/main/java/shop/kkeujeok/kkeujeokbackend/challenge/application/ChallengeService.java
Labels: Bug

#173 Fix(#170): 챌린지 추가 시 챌린지 블록 생성 안되는 오류 해결
  src/main/java/shop/kkeujeok/kkeujeokbackend/challenge/application/ChallengeService.java
Labels: Bug

#179 챌린지 및 개인대시보드 삭제 시 연관 매핑 테이블도 제거 및 검색 시 역순 반환
  src/main/java/shop/kkeujeok/kkeujeokbackend/challenge/application/ChallengeService.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/challenge/domain/Challenge.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/personal/application/PersonalDashboardService.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/personal/domain/PersonalDashboard.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/team/application/TeamDashboardService.java
Labels: Refactor

#180 Refactor(#177): 챌린지 검색 및 전체 조회 시 역순으로 반환하도록 변경
  src/main/java/shop/kkeujeok/kkeujeokbackend/challenge/application/ChallengeService.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/challenge/domain/repository/ChallengeCustomRepositoryImpl.java
Labels: Refactor

#187 Refactor(#168): 블록 디데이 코드 수정
  src/main/java/shop/kkeujeok/kkeujeokbackend/block/api/dto/response/BlockInfoResDto.java
Labels: Refactor

#184 Refactor(#183): 챌린지에 참여하고 그 당일이 챌린지 생성되는 날이면 알림 보낸다
  src/main/java/shop/kkeujeok/kkeujeokbackend/challenge/application/ChallengeService.java
Labels: Refactor

#186 Refactor(#185): 삭제된 대시보드 접근 불가 예외 처리
  src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/domain/Dashboard.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/exception/DashboardDeletedException.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/personal/application/PersonalDashboardService.java
  src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/team/application/TeamDashboardService.java
Labels: Refactor
